### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jayvdb** [theY4Kman/pytest-drf#2]
It would be handy to have some tests, or at least an example in the README

**Comment by theY4Kman** [comment]
Ah, yes, you've caught me red-handed skimping on docs for expediency. Let's see if I can't bang out some tests and make headway on docs this weekend.

**Comment by theY4Kman** [comment]
Alright, I added some tests and fixed a few things. Because I changed how MRO works w/ `APIViewTest`, which is technically a breaking change, I've bumped a major version. It's now available [on PyPI as 1.0.0](https://pypi.org/project/pytest-drf/1.0.0/).

I'll add usage info to the README next. And after that, I'd like to add some sphinx docs, including a quickstart, tutorials, how-to's, and API reference.

Thanks for your interest :) I use this library (well, the private originating source of it) everyday, and it's made API testing/development wonderful. I'm proud of it, and would love for others to find it useful, too. Without you submitting this ticket, I might not've returned to polish it — which I'm glad I did, because I found _several_ bugs (including showstoppers) in the process.

**Comment by jayvdb** [comment]
Ok, I have been looking for a nice DRF testing framework, so I am keen to try it out.

As a side-node, I am trying to switch to pytest-djangoapp instead of pytest-django, partly because the former is better at mocked django for quicker tests (and several of my apps / projects fail on pytest-django without horrible hacks), but also to help ecosystem diversity - I think Django needs multiple base test frameworks, and putting everything in pytest-django is problematic.

I noticed that this project uses pytest-django, but pytest-drf doesnt depend on it.  This was part of why I thought it was worth exploring.  I hope that isnt going to change.

I've started packaging all your pytest plugins at https://build.opensuse.org/project/show/home:jayvdb:pytest

Most of the sdists on PyPI dont include LICENSE or the tests.  Including those in the sdist makes it easier for my tools to fetch from PyPI and run the tests in the RPM build.

**Comment by theY4Kman** [comment]
Oh, wow, [pytest-djangoapp](https://github.com/idlesign/pytest-djangoapp) looks _super_ handy — I could even use it for the tests here. I was not aware of it at all. I use pytest-django for work, and have run into several issues with it, leading to a number of workarounds and hacks. It's good to know someone else recognized the problems it has and addressed them.

And aye, I used pytest-django for the tests here, because it's what I've been familiar with; but pytest-drf is meant to be agnostic to the Django test framework — it merely provides convenient scaffolding for DRF API tests. I believe in having as loose coupling as is possible.

Neat about the packaging! Is that an automated package repo for OpenSUSE?

Noted about including tests and LICENSE in the sdists. I'll make it a point to ensure they're included from now on. For the package repo, how do you know how to run the tests? Is that something I can finagle into `setup.py test`? I usually use [poetry](https://python-poetry.org/) for python dep mgmt / build system; maybe they've got support for making `setup.py test` work with pytest (and tox).

**Comment by theY4Kman** [comment]
FYI: [this example `ViewSetTest` in the tests](https://github.com/theY4Kman/pytest-drf/blob/554d7f80f76d199a88dc9fb131c05bf762468700/tests/pytest_drf/test_views.py#L82-L301) largely resembles what I write professionally. What makes pytest-drf "scaffolding" is that those `ViewSetTests` can be written before ever writing the `ViewSet` — building a declarative description of what the `ViewSet` _would_ act like, then serving as red/green tests providing feedback until the `ViewSet` is complete.

**Comment by jayvdb** [comment]
pytest-djangoapp is a bit "green", but I find that useful also - I prefer to build new fixtures than trying to undo/workaround fixtures which are forced upon me.

The openSUSE package repo is my own, and is semi-automated, but Python packages rarely are well described, and often add pins which need to be removed to work with the rest of the Python ecosystem.  While `python setup.py test` is default in my template, I often have to switch to `pytest`.  pytest-runner is currently the best of both worlds, because then `setup.py test` will check dependency versions on the build image, and then pytest takes over.  Dependency versions is one of the hardest parts of distro packaging, so much so that many packagers ignore it, and then packages break frequently but they rely on the 'rolling' nature of the release to get those bugs sorted out.  `setup.py test` lets me see when upstream dep versions have changed, including their `< x.y` pins.  But `pytest-runner` says it is deprecated, and I am more than happy to just run `pytest`.

My current project is heavily reliant on model-bakery for data.  There is a bakery->factoryboy bridge/integration that I tried to get working at one stage.  I might re-attempt that.

**Comment by theY4Kman** [comment]
Alright, I finally expanded [the README](https://github.com/theY4Kman/pytest-drf/blob/7659a3e7ccb72fc9935b013d76a7f610303d8b38/README.md) — whatcha think, @jayvdb ?

**Comment by theY4Kman** [comment]
Gonna close this to be a good bookkeeper, since tests and README examples have been added
